### ISSUE TITLE
IntelliJ erkennt Code nicht als Java

### ISSUE THREAD

**Issue by rinkseb** [smorfer/QuizGame#2]
@smorfer 

Wo kann ich IntelliJ sagen, dass der Code ein JavaCode ist?

**Comment by smorfer** [comment]
Du musst das Projekt/die Dateien als Java Code markieren, Google ist dabei auch eine Hilfe.

**Comment by smorfer** [comment]
Warte ist der src Ordner blau?

**Comment by rinkseb** [comment]
Nee, orange

**Comment by rinkseb** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/20124012/16534364/7fdd6ed2-3fdf-11e6-8e67-982078d83a17.JPG)

**Comment by smorfer** [comment]
Dann drauf drücken mit rechts, und suchen nach "Mark as..." Und dann als source markieren

**Comment by rinkseb** [comment]
Danke funktioniert
