### ISSUE TITLE
Fehlende klasse "Sortierte Liste"?

### ISSUE THREAD

**Issue by xmichi29** [smorfer/QuizGame#3]
Fehlt uns nicht noch eine Klasse auf die dann highscorelist oder questions zugreifen?
Wenn ihr in früheren BlueJ Projekten nachschaut haben wir da eine klasse "Sortierte Liste" gehabt. auf die die o.g. Klassen zugreifen und diese "Sortierte Liste" dann mit "erster,methode()" die Rekursion gestartet hat, 
Uns fehlt so eine "Zwischenklasse", weil wir nur highscorelist und questions haben, die beide mit "erster.methode()" auf den Baum zugreifen wollen.
![quiz](https://cloud.githubusercontent.com/assets/20074934/16818980/96ade866-494a-11e6-8054-5a139d799540.jpeg)

**Comment by smorfer** [comment]
Ich verstehe nicht ganz, questions und Highscorelist benutzen einfach ein Objekt auf der Liste, deklarieren es als erster und benutzen seine Methoden, dazu brauchen wir doch keine Zwischenklasse?

**Comment by rinkseb** [comment]
Wir hatten die Klasse irgendwie immer, aber die macht keinen Sinn, ich hab die immer weggelassen.
Die brauchen wir nicht, die macht ja nichts anderes, als die Liste die Methoden in der Liste aufzurufen.
Mann kann des natürlich so machen, aber ich denke, dass das überflüssig ist.

**Comment by rinkseb** [comment]
Wobei wir sie eigentlich einfügen könnten, sodass die ganzen Methoden nich zweimal in Highscorelist und Questions geschrieben werden müssen, dass muss Derjenige entscheiden, der die Liste implementiert.

Wer macht das?

**Comment by flogi2016** [comment]
Ich mach die highscore und score Klassen, Michi machst du die Liste ? Ich
weiß es grad gar nicht 😁

Am 14.07.2016 16:15 schrieb "rinkseb" notifications@github.com:

**Comment by xmichi29** [comment]
Ja ich mach scheinbar den Rest :D

**Comment by flogi2016** [comment]
Hahaha okay gut, ich war mir jetzt nimmer ganz sicher

Am 14.07.2016 16:23 schrieb "xmichi29" notifications@github.com:

**Comment by rinkseb** [comment]
Machen wir´s mit der Klasse "sortierteListe"?
Is wichtig dafür wichtig, wie ich "Questions" implementiere.
Ich glaube, es ist fast besser mit der Klasse.

**Comment by xmichi29** [comment]
Die Klasse wird einfach nur List heißen

**Comment by rinkseb** [comment]
OK danke
