### ISSUE TITLE
Inhalt der question files gelöscht

### ISSUE THREAD

**Issue by xmichi29** [smorfer/QuizGame#6]
Hey sebastian gibt es einen Grund, warum du die Fragen aus den questionX.txt gelöscht hast?

**Comment by rinkseb** [comment]
Nein, die waren gar nicht da, ich hab die Dateien hinzugefügt, um nen Testlauf zu machen, es war lediglich Questions6.txt vorhanden

**Comment by xmichi29** [comment]
Komisch... Ich hab eigentlich die ersten 5 Dateien gemacht

Am 19.07.2016 10:06 nachm. schrieb "rinkseb" notifications@github.com:

**Comment by rinkseb** [comment]
Vielleich wurden sie nicht vollständig hochgepusht, und sind noch offline

**Comment by rinkseb** [comment]
Könnt ihr ja morgen nachschauen.
Ich bin morgen nicht da, könnt ihr das Projekt soweit bringen, dass wir kompellieren können?
Von Meinerseite müsste hoffentlich alles passen, wenn nicht könnt ihr dass dann einfach ändern.
