### ISSUE TITLE
Ich kann nicht starten

### ISSUE THREAD

**Issue by rinkseb** [smorfer/QuizGame#7]
Ich kann compilen, aber wenn ich starten will, kommt immer diese Fehlermeldeung:
`Exception in thread "main" java.lang.ExceptionInInitializerError`
    `at com.failexe.GUI.GUI.<init>(GUI.java:39)`
    `at Controller.<clinit>(Controller.java:8)`
    `at java.lang.Class.forName0(Native Method)`
    `at java.lang.Class.forName(Class.java:264)`
    `at com.intellij.rt.execution.application.AppMain.main(AppMain.java:122)`
`Caused by: java.lang.IllegalStateException: Toolkit not initialized`
    `at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:273)`
    `at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:268)`
    `at com.sun.javafx.application.PlatformImpl.setPlatformUserAgentStylesheet(PlatformImpl.java:550)`
    `at com.sun.javafx.application.PlatformImpl.setDefaultPlatformUserAgentStylesheet(PlatformImpl.java:512)`
    `at javafx.scene.control.Control.<clinit>(Control.java:87)`
    `... 5 more`

Die sich auf diese Codezeile in der Klasse `GUI` bezieht:
`Label QuestionLabel = new Label();`

Ich habe schon im Internet un überall gesucht, und es mit verschieden Sachen probiert zu beheben, es hat nicht geklappt, worad könnte das liegen?

**Comment by xmichi29** [comment]
Komisch eigentlich wurde nix mehr geändert...

Am 22.07.2016 3:54 nachm. schrieb "rinkseb" notifications@github.com:

**Comment by xmichi29** [comment]
Meine Fehlermeldung:

Exception in thread "main" java.lang.ClassNotFoundException: Controller
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:123)

**Comment by rinkseb** [comment]
Dass lässt sich beheben:
1. Linksklick auf QuizGame (in IntelliJ) -> new  -> directory
2. Name: out
3. File -> Project Structure -> Modules -> Paths
4. -> Use module compile output path
5. Füge bei Outputpath den Pfad von dem neu erzeugten Ordner "out" ein
6. Apply und fertig

**Comment by xmichi29** [comment]
oke wir sind jetzt auf dem gleichen stand der probleme :+1:

**Comment by xmichi29** [comment]
Noch niemand eine Lösung gefunden?
Anscheinend wird irgendeine static Variable nicht initialisiert (falls es jemandem hilft)...

**Comment by rinkseb** [comment]
Nee ... 
Immer noch dasselbe Problem

**Comment by smorfer** [comment]
Ich glaube ihr müsst die Initialisierung außerhalb der start method machen

**Comment by smorfer** [comment]
Bzw. die init muss in start sein, glaub ich, ansonsten vlt noch static machen probieren, solche Sachen

**Comment by rinkseb** [comment]
Mit dem geänderten Code läuft´s jetzt einwandfrei bei mir, ich musste aber die Umlaute in den txt-Dateien wieder ausbessern, erst dann hat´s fumktioniert.
